#include <furi.h>
#include <furi_hal.h>

#include <gui/gui.h>
#include <input/input.h>
#include <notification/notification.h>
#include <notification/notification_messages.h>

#include <assets_icons.h>
#include <gui/elements.h>

#include <time.h> /* clock_gettime(), time() */
#include <sys/time.h> /* gethrtime(), gettimeofday() */


/* Magic happens here -- this file is generated by fbt.
 * Just set fap_icon_assets in application.fam and #include {APPID}_icons.h */
#include "coinflip_icons.h"

typedef struct {
    int32_t x, y;
} ImagePosition;

static ImagePosition image_position = {.x = 12, .y = 30};
static ImagePosition smoke_position = {.x = 0, .y = 0};


typedef struct {
    int32_t counter, maxdrags;
    bool lit, done;
    IconAnimation* icon;
} Cigarette;

typedef struct {
    int32_t counter, counter_heads, counter_tails;
    bool flipped, heads;
    IconAnimation* icon;
} Coin;

static Cigarette cigarette = {.counter = 0, .maxdrags = 13, .lit = false, .done = false};

static Coin coin = {.counter = 0, .counter_heads = 0, .counter_tails = 0, .flipped = 0, .heads = 0};

const NotificationMessage message_delay_15 = {
    .type = NotificationMessageTypeDelay,
    .data.delay.length = 15,
};



static const NotificationSequence coinflip_start = {
    //&message_note_ds2,
    //&message_delay_25,
    //&message_sound_off,

    &message_vibro_on,
    &message_delay_25,
    &message_vibro_off,

    //&message_green_255,
    //&message_delay_25,
    //&message_green_0,

    &message_blink_start_10,
    &message_blink_set_color_magenta,
    &message_delay_100,
    &message_blink_stop,

    NULL,
};

static const NotificationSequence coinflip_stop = {
    &message_blink_stop,
    NULL,
};


static void app_draw_callback(Canvas* canvas, void* ctx) {
    UNUSED(ctx);

    canvas_clear(canvas);

    
    if (coin.heads == true){
        // HEADS
        canvas_draw_circle(canvas, 64, 25, 24);
        canvas_draw_circle(canvas, 64, 25, 18);
        canvas_set_font(canvas, FontPrimary);
        canvas_draw_str(canvas, 50, 29, "heads");
    } else if (coin.heads == false) {
        // TAILS
        canvas_draw_circle(canvas, 64, 25, 24);
        canvas_draw_circle(canvas, 64, 25, 18);
        canvas_set_font(canvas, FontPrimary);
        canvas_draw_str(canvas, 55, 29, "tails");
    }


    // flip button
    elements_button_center(canvas, "flip");

  
}

bool random_flip() {
    // Generate a random number (0 or 1)
    return rand() % 2 == 0; // 0 means false, 1 means true
}



static void app_input_callback(InputEvent* input_event, void* ctx) {
    furi_assert(ctx);

    FuriMessageQueue* event_queue = ctx;
    furi_message_queue_put(event_queue, input_event, FuriWaitForever);
}

int32_t coinflip_main(void* p) {
    UNUSED(p);
    FuriMessageQueue* event_queue = furi_message_queue_alloc(8, sizeof(InputEvent));

    //cigarette.icon = icon_animation_alloc(&A_cigarette_smoke);

    // Configure view port
    ViewPort* view_port = view_port_alloc();
    view_port_draw_callback_set(view_port, app_draw_callback, NULL);
    view_port_input_callback_set(view_port, app_input_callback, event_queue);

    // Register view port in GUI
    Gui* gui = furi_record_open(RECORD_GUI);
    gui_add_view_port(gui, view_port, GuiLayerFullscreen);

    NotificationApp* notification = furi_record_open(RECORD_NOTIFICATION);

    InputEvent event;

    bool running = true;
    while(running) {
        if(furi_message_queue_get(event_queue, &event, 100) == FuriStatusOk) {
            if((event.type == InputTypePress) || (event.type == InputTypeRepeat)) {
                switch(event.key) {
                case InputKeyLeft:
                    cigarette.counter = 0;
                    cigarette.lit = 0;
                    cigarette.done = false;
                    smoke_position.x = 0;
                    image_position.x = 12;
                    icon_animation_stop(cigarette.icon);
                    break;
                case InputKeyRight:
                    break;
                case InputKeyUp:
                    break;
                case InputKeyDown:
                    break;
                case InputKeyOk:
                    notification_message(notification, &coinflip_start);
                    coin.heads = random_flip();
                    notification_message(notification, &coinflip_stop);
                    //icon_animation_start(cigarette.icon);
                    break;
                default:
                    running = false;
                    break;
                }
            }
        }
        view_port_update(view_port);
    }

    view_port_enabled_set(view_port, false);
    gui_remove_view_port(gui, view_port);
    view_port_free(view_port);
    furi_message_queue_free(event_queue);

    furi_record_close(RECORD_GUI);

    return 0;
}
